[global]
  add_to_hermes = false
  auto_maintain_config = true
  extra_wallets = 2
  gaiad_binary = "/usr/bin/interchain-queriesd"
  hdpath = ""
  home_dir = "/.gm"
  ports_start_at = 27000
  validator_mnemonic = "useful amused panda recycle swallow dirt avoid unlock elbow shove letter able salt keen avocado grace hub three loan range crucial hazard buzz cigar"
  wallet_mnemonic = "heavy service saddle age obscure actress purse whip summer disease leader punch blue border wreck garage search miss inform pear tumble guide stone version"
   
  [global.hermes]
    binary = "/usr/bin/hermes" #change this path according to your setup
    config = "/.hermes/config.toml"
    log_level = "info"
    telemetry_enabled = true
    telemetry_host = "127.0.0.1"
    telemetry_port = 3001
 
 [ibc-0]
   ports_start_at = 27010
 
 [ibc-1]
   ports_start_at = 27020
 
 [node-0]
   add_to_hermes = true
   network = "ibc-0"
   ports_start_at = 27030
 
[node-1]
  add_to_hermes = true
  network = "ibc-1"
  ports_start_at = 27040
